version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - mobiauto-network
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - '8080:8080'
    networks:
      - mobiauto-network
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      LIQUIBASE_CHANGELOG: db/liquibase-changelog.xml
      LIQUIBASE_URL: jdbc:postgresql://localhost:5432/db
      LIQUIBASE_USER: myuser
      LIQUIBASE_PASSWORD: mypassword
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  mobiauto-network:
    driver: bridge

volumes:
  db-data: